#!/usr/bin/ruby

puts 'Euler #171'
puts

def f n
   return n.to_s.split('').map(&:to_i).map{|x| x*x}.reduce(:+)
end

def fac n
   return n.downto(1).inject(:+)
end

puts "Tests:"
TESTS=[3, 25, 442]
TESTS.each { |val| puts "f(#{val}) = #{f val }" }
puts 

BASE_DIGITS=(1..9).to_a

(1..20).each { |l|
p BASE_DIGITS.repeated_combination(20).lazy.count
